== Epilogue

[quote, Winston Churchill]
____
Now this is not the end. It is not even the beginning of the end. pass:[<phrase role='keep-together'>But it is, perhaps, the end of the beginning.</phrase>]
____

Enterprise Java is, as technologies go, not a highly opinionated landscape; it does not prescribe only one way of accomplishing a task.  Although Java EE provides a suite of APIs, we've seen in our GeekSeek example that it may be appropriate to look outside the platform and integrate with external frameworks.  This freedom carries with it a burden of choice: developers new and seasoned alike may find that bringing together a working application at all layers may carry complexity.

We've set out to show one cohesive application, but this is not a book of best practices.  We've taken one approach of many, and it fit our requirements.

What we _do_ intend to underscore is the importance the role of testing takes in responsible development.  The applications we deploy into production are composed of much more than what we write on our own; we need to be sure that all components are working in concert.  Additionally, it's helpful to isolate business logic where we can, and further ensure that everything is connected properly when integrated.  The Arquillian project in particular has been a wonderful means for us to explore the bounds of how simple we can make testing of even the most complex use cases, and its community has been instrumental in pushing the limits of testability in a landscape that has historically been cumbersome to manipulate.

We hope that the techniques outlined here, on the companion source repository, and running proof in production on http://geekseek.continuousdev.org are beneficial to your own path in building reliable applications in Enterprise Java.