== Continuous Enterprise Development in Java

=== O'Reilly Media

|==========================================================================================
| Andrew Lee Rubinger | +alr@continuousdev.org+ | http://twitter.com/ALRubinger['@ALRubinger']
| Aslak Knutsen | +aslak@continuousdev.org+ | http://twitter.com/aslakknutsen['@aslakknutsen']
|==========================================================================================

The authoritative Git repository containing the book and example application source for "Continuous Enterprise Development in Java" by Andrew Lee Rubinger and Aslak Knutsen, published by O'Reilly Media, is hosted by our friends at http://www.github.com[GitHub] at https://github.com/arquillian/continuous-enterprise-development[https://github.com/arquillian/continuous-enterprise-development].  The accompanying book site for this text is located at http://continuousdev.org[http://continuousdev.org], and the official Twitter channel is http://twitter.com/ContinuousDev[@ContinuousDev].  The authors may be reached at authors@continuousdev.org.

All contents of this repository licensed under http://creativecommons.org/licenses/by-sa/2.0/['Creative Commons Attribution-ShareAlike 2.0 Generic'], and we invite the community at large to contribute work including feature requests, typographical error corrections, and enhancements via our https://github.com/arquillian/continuous-enterprise-development/issues[GitHub Issue Tracker].

The official distribution for the book will be available in print and electronic formats via http://shop.oreilly.com/product/0636920025368.do[O'Reilly] or various 3rd-party retailers in September 2013.  The Early Access Release has been open for purchase since the Fall of 2012.

The print release of the book and its example is set to be given the Git tag of +1.0.0+ in this repository, and development will continue thereafter in the +master+ branch to correct errata and add supplmentary material including new chapters and use cases.  The community is welcome to suggest or request topics for additional coverage.

The example application accompanying the use cases raised in the text is called GeekSeek, and is publicly-available at http://geekseek.continuousdev.org[http://geekseek.continuousdev.org].  The source is located in this repository under +code/application+, and instructions for building, testing, and running locally are detailed in https://github.com/arquillian/continuous-enterprise-development/blob/master/Chapter04-RequirementsAndExampleApplication.asciidoc[Chapter 4].

We welcome your contributions and hope you find the material covered here to be of interest and benefit to your work and career in testable enterprise development.
